---
- name: Create multiple users with static password and grant sudo privileges
  hosts: all
  become: true
  vars:
    users:
      - username: kamote11
      - username: kamote12
      - username: bob13
      - username: gmail14
    password_clear: "test123"
  tasks:
    - name: Generate password hash using passlib for static password
      ansible.builtin.set_fact:
        password_hash: "{{ password_clear | community.general.password_hash('sha512') }}"

    - name: Ensure all users exist with specified static password
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ password_hash }}"
        shell: /bin/bash
      loop: "{{ users }}"

    - name: Allow users passwordless sudo via visudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers.d/{{ item.username }}
        line: '{{ item.username }} ALL=(ALL) NOPASSWD:ALL'
        create: yes
        mode: '0440'
      loop: "{{ users }}"

    - name: Allow users sudo via visudo (with password)
      ansible.builtin.lineinfile:
        dest: /etc/sudoers.d/{{ item.username }}
        line: '{{ item.username }} ALL=(ALL:ALL) ALL'
        create: yes
        mode: '0440'
      loop: "{{ users }}"
