---
- name: Create multiple user accounts in Linux with individual passwords
  hosts: all
  become: true
  vars:
    users:
      - username: kurimaw
        password_clear: "kuriTest@2025"
      - username: alice
        password_clear: "alicePass#2025"
      - username: bob
        password_clear: "bobSecure$2025"
      - username: eve
        password_clear: "evePwd!2025"
  tasks:
    - name: Generate password hashes for all users using passlib (community.general collection required)
      ansible.builtin.set_fact:
        user_hashes: "{{ user_hashes | default({}) | combine({ item.username: (item.password_clear | community.general.password_hash('sha512')) }) }}"
      loop: "{{ users }}"

    - name: Ensure all users exist with their individual passwords
      ansible.builtin.user:
        name: "{{ item.username }}"
        password: "{{ user_hashes[item.username] }}"
        shell: /bin/bash
      loop: "{{ users }}"

    - name: Allow users passwordless sudo via visudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers.d/{{ item.username }}
        line: '{{ item.username }} ALL=(ALL) NOPASSWD:ALL'
        create: yes
        mode: '0440'
      loop: "{{ users }}"

    - name: Allow users sudo via visudo (with password)
      ansible.builtin.lineinfile:
        dest: /etc/sudoers.d/{{ item.username }}
        line: '{{ item.username }} ALL=(ALL:ALL) ALL'
        create: yes
        mode: '0440'
      loop: "{{ users }}"
