---
- name: Create user, set password, and grant sudo privileges
  hosts: all
  become: true
  vars:
    username: jumpman
    password_clear: "test1"
  tasks:
    - name: Generate password hash
      ansible.builtin.set_fact:
        password_hash: "{{ password_clear | password_hash('sha512') }}"

    - name: Ensure user exists with specified password
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password_hash }}"
        shell: /bin/bash

    - name: Add user to sudo group
      ansible.builtin.user:
        name: "{{ username }}"
        groups: sudo
        append: yes

    - name: Allow user passwordless sudo via visudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers.d/{{ username }}
        line: '{{ username }} ALL=(ALL) NOPASSWD:ALL'
        create: yes
        mode: '0440'
